/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M21
 * Generated at: 2017-06-17 02:13:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Register;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Register_005finterface_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>浪翼的小书屋</title>\r\n");
      out.write("</head>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("       function userCheck()\r\n");
      out.write("       {\r\n");
      out.write("    \t   if(form_register.username.value==\"\")\r\n");
      out.write("    \t   {\r\n");
      out.write("    \t       window.alert(\"用户名不能为空！\");\r\n");
      out.write("    \t       return false;\r\n");
      out.write("    \t   }\r\n");
      out.write("    \t   if(form_register.password.value==\"\")\r\n");
      out.write("\t\t   {\r\n");
      out.write("\t\t       window.alert(\"密码不能为空！\");\r\n");
      out.write("\t\t       return false;\r\n");
      out.write("\t\t   }\r\n");
      out.write("    \t   if(form_register.again_password.value==\"\")\r\n");
      out.write("\t\t   {\r\n");
      out.write("\t\t       window.alert(\"请确认密码！\");\r\n");
      out.write("\t\t       return false;\r\n");
      out.write("\t\t   }\r\n");
      out.write("    \t   if(form_register.email.value==\"\")\r\n");
      out.write("\t\t   {\r\n");
      out.write("\t\t       window.alert(\"邮箱不能为空！\");\r\n");
      out.write("\t\t       return false;\r\n");
      out.write("\t\t   }\r\n");
      out.write("    \t   var target=document.getElementsByTagName(\"option\")[0];\r\n");
      out.write("    \t       if(target.selected)\r\n");
      out.write("    \t    \t   {\r\n");
      out.write("    \t    \t   window.alert(\"请选择一个邮箱域名！\");\r\n");
      out.write("    \t    \t   return false;\r\n");
      out.write("    \t    \t   }\r\n");
      out.write("    \t   if(form_register.password.value!=form_register.again_password.value)\r\n");
      out.write("    \t   {\r\n");
      out.write("    \t\t   window.alert(\"两次输入的密码不同，请重新输入！\");\r\n");
      out.write("    \t\t   return false;\r\n");
      out.write("    \t   }\r\n");
      out.write("    \t   \r\n");
      out.write("    \t   if(form_register.question.value==\"\")\r\n");
      out.write("\t\t   {\r\n");
      out.write("\t\t       window.alert(\"密保问题不能为空！\");\r\n");
      out.write("\t\t       return false;\r\n");
      out.write("\t\t   }\r\n");
      out.write("    \t   if(form_register.answer.value==\"\")\r\n");
      out.write("\t\t   {\r\n");
      out.write("\t\t       window.alert(\"密保答案不能为空！\");\r\n");
      out.write("\t\t       return false;\r\n");
      out.write("\t\t   }\r\n");
      out.write("    \t   \r\n");
      out.write("    \t   return true;\r\n");
      out.write("       }\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t<h3 style=\"font-family: 楷体\">新用户注册</h3>\r\n");
      out.write("\t\t<form action=\"RegisterServlet\" target=\"_top\" name=\"form_register\" method=\"post\"\r\n");
      out.write("\t\t\tonsubmit=\"return userCheck()\">\r\n");
      out.write("\t\t\t<table border=\"0\" style=\"font-family: 楷体\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>用户名</td>\r\n");
      out.write("\t\t\t\t\t<td><input name=\"username\" type=\"text\" size=20> <font\r\n");
      out.write("\t\t\t\t\t\tcolor=\"red\">*</font></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>密码</td>\r\n");
      out.write("\t\t\t\t\t<td><input name=\"password\" type=\"password\" size=20> <font\r\n");
      out.write("\t\t\t\t\t\tcolor=\"red\">*</font></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>确认密码</td>\r\n");
      out.write("\t\t\t\t\t<td><input name=\"again_password\" type=\"password\" size=20>\r\n");
      out.write("\t\t\t\t\t\t<font color=\"red\">*</font></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>邮箱</td>\r\n");
      out.write("\t\t\t\t\t<td><input name=\"email\" type=\"text\" size=20> <select\r\n");
      out.write("\t\t\t\t\t\tname=\"email2\" style=\"font-family: 楷体\">\r\n");
      out.write("\t\t\t\t\t\t\t<option>--请选择邮箱域名--</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>@qq.com</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>@163.com</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>@126.com</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>@sina.com</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>@sina.cn</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>@yahoo.com.cn</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>@gmail.com</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>@sohu.com</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>@hotmail.com</option>\r\n");
      out.write("\t\t\t\t\t</select> <font color=\"red\">*</font></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>设置密保问题</td>\r\n");
      out.write("\t\t\t\t\t<td><input name=\"question\" type=\"text\" size=20>\r\n");
      out.write("\t\t\t\t\t\t<font color=\"red\">*</font></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>设置密保答案</td>\r\n");
      out.write("\t\t\t\t\t<td><input name=\"answer\" type=\"text\" size=20>\r\n");
      out.write("\t\t\t\t\t\t<font color=\"red\">*</font></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"submit\" value=\"注册\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t<td>注意：<font color=\"red\">*</font>为必填\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</center>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
