/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M21
 * Generated at: 2017-06-17 04:08:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Personal_005fcenter;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import connectDB.Alter_imformation;

public final class alter_005fimformation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("connectDB.Alter_imformation");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title></title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("      ");
Alter_imformation a=new Alter_imformation();
      String user=(String)session.getAttribute("login_name");
      System.out.print(user+"!!!");
      a.getuser(user);
      String check1="";
      String check2="";
      String check3="";
      String check="";
      if(a.getsex().equals("male"))
    	  check1="checked";
      else if(a.getsex().equals("female"))
    	  check2="checked";
      else if(a.getsex().equals("gay"))
    	  check3="checked";
      else check="no";
      
      out.write("\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t<form action=\"PersonalServlet\" style=\"font-family: 楷体\" method=\"post\">\r\n");
      out.write("\t\t\t昵称<input name=\"nickname\" type=\"text\" value=\"");
      out.print(a.getnickname());
      out.write("\"> <br>\r\n");
      out.write("\t\t\t");
if(check1.equals("checked")) {
      out.write("\r\n");
      out.write("\t\t\t<br> <br> <input name=\"sex\" type=\"radio\" value=\"male\" checked=\"checked\">男神\r\n");
      out.write("\t\t\t<input name=\"sex\" type=\"radio\" value=\"female\" >女神 <input\r\n");
      out.write("\t\t\t\tname=\"sex\" type=\"radio\" value=\"gay\">其他 <br> <br>\r\n");
      out.write("\t        ");
} 
      out.write("\r\n");
      out.write("\t        ");
if(check2.equals("checked")) {
      out.write("\r\n");
      out.write("\t\t\t<br> <br> <input name=\"sex\" type=\"radio\" value=\"male\" >男神\r\n");
      out.write("\t\t\t<input name=\"sex\" type=\"radio\" value=\"female\" checked=\"checked\">女神 <input\r\n");
      out.write("\t\t\t\tname=\"sex\" type=\"radio\" value=\"gay\">其他 <br> <br>\r\n");
      out.write("\t        ");
} 
      out.write("\r\n");
      out.write("\t        ");
if(check3.equals("checked")) {
      out.write("\r\n");
      out.write("\t\t\t<br> <br> <input name=\"sex\" type=\"radio\" value=\"male\" >男神\r\n");
      out.write("\t\t\t<input name=\"sex\" type=\"radio\" value=\"female\" >女神 <input\r\n");
      out.write("\t\t\t\tname=\"sex\" type=\"radio\" value=\"gay\" checked=\"checked\">其他 <br> <br>\r\n");
      out.write("\t        ");
} 
      out.write("\r\n");
      out.write("\t         ");
if(check.equals("no")) {
      out.write("\r\n");
      out.write("\t\t\t<br> <br> <input name=\"sex\" type=\"radio\" value=\"male\" >男神\r\n");
      out.write("\t\t\t<input name=\"sex\" type=\"radio\" value=\"female\">女神 <input\r\n");
      out.write("\t\t\t\tname=\"sex\" type=\"radio\" value=\"gay\">其他 <br> <br>\r\n");
      out.write("\t        ");
} 
      out.write("\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"保存\">\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
